#!/bin/sh

# chkconfig: 2345 20 80
# description: Tool Integration Backend Service

. /etc/init.d/functions

#Paths zoidberg.js, pidfile, and lockfile.
program=zoidberg
launch=/usr/local/bin/node-launch.py
node=/usr/local/bin/node
zoid=/usr/local/lib/node/iplant-zoidberg/zoidberg.js
conf=/etc/iplant-zoidberg.conf
pidfile=/var/run/zoidberg.pid
lockfile=/var/lock/subsys/zoidberg
RETVAL=0

start () {
    echo -n $"Starting $program: "
    daemon ${launch} ${node} ${zoid} ${conf}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}
    return $RETVAL
}

stop () {
    echo -n $"Stopping $program: "
    killproc -p ${pidfile}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -rf ${lockfile} ${pidfile}
}

restart () {
    echo -n $"Restarting $program: "
    stop
    start
}

showstatus () {
    status -p ${pidfile} ${program}
    RETVAL=$?
}

case "$1" in
    start)
        start
    ;;
    
    stop)
        stop
    ;;
    
    restart)
        restart
    ;;
    
    status)
        showstatus
    ;;
    
    *)
        echo "Usage: iplant-zoidberg {start|stop|restart,status}"
        exit 1
    ;;
esac

exit $RETVAL
